### ISSUE TITLE
Questions about Logon Restrictions for Domain Controllers

### ISSUE THREAD

**Issue by StefanSa** [unassassinable/PAW#5]
Hi rich,
At "03 - Logon Restrictions" you write:
Ensure the Domain Controllers group is a member of the All-Tier0 Servers group

This would affect two GPOs on the domain controllers.
-Security - Logon Restrictions - Domain Controllers
-Security - Logon Restrictions - Servers Tier 0

If that were correct, is there no problem with

Log on as batch job
    BUILTIN\Administrators
    LogOnAsBatch - This is a **local group** that we will create in a subsequent GPO.

Log on as a service
    NT SERVICE\ALL Services
    LogOnAsService - This is a **local group** that we will create in a subsequent GPO.

on the domain controller?

**Comment by utsecnet** [comment]
No, adding the DCs to the all-tier0-servers group will not be a problem.
The logonas groups will just not get created in the DCs and will be
ignored.

**Comment by StefanSa** [comment]
rich,
parts of these GPOs are overwritten by the default domain controller gpo.
Such as:
-Allow log on locally:
--BUILTIN\Administrators
--DOMAIN\PAW-Tier0-Admins

Right ?

**Comment by utsecnet** [comment]
No, you put the default gpo on the bottom of the gpo inheritance, and
baselines go above so that they overwrite the default.  Remember, baselines
are the "bare minimum" level you accept as secure.  So you will often have
many gpos that over ride the baselines.  These would go above the baselines
in the inheritance list.

As a general rule try to keep the linked group policy objects organization
like so:

* One off rules
* Baseline rules
* Default rules

**Comment by StefanSa** [comment]
Ok, this work.
Again thx for your help
